"""users table

Revision ID: 222e3417e293
Revises: 997efda45d78
Create Date: 2020-09-30 16:53:43.720212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222e3417e293'
down_revision = '997efda45d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_status'), 'user', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_status'), table_name='user')
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
