"""users table

Revision ID: 997efda45d78
Revises: 
Create Date: 2020-09-30 13:39:52.147693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997efda45d78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fb_id', sa.String(length=64), nullable=True),
    sa.Column('fio', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_fb_id'), 'user', ['fb_id'], unique=True)
    op.create_index(op.f('ix_user_fio'), 'user', ['fio'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_fio'), table_name='user')
    op.drop_index(op.f('ix_user_fb_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
